# version: '3.3'

services:
  db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: 'project_db'
    restart: on-failure
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: cs4640LocalUser!
      POSTGRES_DB: example
      TZ: "America/New_York"
    volumes:
      - db-data:/var/lib/postgresql # removed extra /data !!!
  php:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    container_name: 'project_web'
    ports:
      - 8000:80
    volumes:
      - ./web/src/:/opt/src/
      - ./web/www/:/var/www/html/
      - ./web/cgi-bin/:/usr/lib/cgi-bin/
      - ./web/log/:/opt/log/
    depends_on:
      - db
    environment:
      TZ: "America/New_York"
volumes:
  db-data:
